name: Build and deploy ASP.Net Core app to Azure Web App - taskhive

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Backend/TodoApp.API/TodoApp.API/TodoApp.API

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: Backend/TodoApp.API/TodoApp.API/TodoApp.API

      - name: Publish the app
        run: dotnet publish -c Release -o "${{ github.workspace }}/Backend/TodoApp.API/TodoApp.API/publish"
        working-directory: Backend/TodoApp.API/TodoApp.API/TodoApp.API 

      - name: List contents of publish folder
        run: dir ${{ github.workspace }}/Backend/TodoApp.API/TodoApp.API/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/Backend/TodoApp.API/TodoApp.API/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BF5A976542849FB82E4C70C82D14EDB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6127A0582AF54EBD87E2E8847E08F178 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3DF320768F694144A4DA4F51C08E32CD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taskhive'
          slot-name: 'Production'
          package: ${{ github.workspace }}/Backend/TodoApp.API/TodoApp.API/publish