name: Build and deploy ASP.Net Core app to Azure Web App - taskhive

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Application'
        steps:
          - task: VSBuild@1
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/t:Restore /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

  - stage: Publish
    displayName: 'Publish Stage'
    dependsOn: Build
    jobs:
      - job: PublishJob
        displayName: 'Publish Application'
        steps:
          - script: dotnet build --configuration $(buildConfiguration)
            displayName: 'Build the application using dotnet'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true
              configuration: $(buildConfiguration)
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '29ed8cec-f3a2-4dac-a518-bcd1f6cc3581'
              appType: 'webApp'
              appName: 'taskhive'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
